querry = """

BEGIN;


ALTER TABLE IF EXISTS public.game_rounds DROP CONSTRAINT IF EXISTS game_rounds_game_id_fkey;

ALTER TABLE IF EXISTS public.game_rounds DROP CONSTRAINT IF EXISTS game_rounds_round_id_fkey;

ALTER TABLE IF EXISTS public.games DROP CONSTRAINT IF EXISTS games_user_id_fkey;

ALTER TABLE IF EXISTS public.games DROP CONSTRAINT IF EXISTS games_word_id_fkey;

ALTER TABLE IF EXISTS public.prises DROP CONSTRAINT IF EXISTS prises_categorie_id_fkey;

ALTER TABLE IF EXISTS public.rounds DROP CONSTRAINT IF EXISTS rounds_prise_id_fkey;



DROP TABLE IF EXISTS public.categorie;

CREATE TABLE IF NOT EXISTS public.categorie
(
    categorie_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    categorie_name character varying COLLATE pg_catalog."default",
    CONSTRAINT categorie_pkey PRIMARY KEY (categorie_id)
);

DROP TABLE IF EXISTS public.game_rounds;

CREATE TABLE IF NOT EXISTS public.game_rounds
(
    game_id integer,
    round_id smallint
);

DROP TABLE IF EXISTS public.games;

CREATE TABLE IF NOT EXISTS public.games
(
    game_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    word_id integer,
    user_id integer,
    letters "char"[],
    CONSTRAINT games_pkey PRIMARY KEY (game_id)
);

DROP TABLE IF EXISTS public.prises;

CREATE TABLE IF NOT EXISTS public.prises
(
    prise_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    prise_description character varying COLLATE pg_catalog."default",
    discount_value integer,
    price_in_scores integer,
    categorie_id integer,
    to_show boolean DEFAULT true,
    CONSTRAINT prises_pkey PRIMARY KEY (prise_id)
);

DROP TABLE IF EXISTS public.rounds;

CREATE TABLE IF NOT EXISTS public.rounds
(
    round_id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    round_scores integer,
    is_word_guessed boolean NOT NULL DEFAULT false,
    prise_id integer,
    CONSTRAINT rounds_pkey PRIMARY KEY (round_id)
);

DROP TABLE IF EXISTS public.scores;

CREATE TABLE IF NOT EXISTS public.scores
(
    score_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    score integer NOT NULL,
    CONSTRAINT scores_pkey PRIMARY KEY (score_id)
);

DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_name character varying COLLATE pg_catalog."default",
    password character varying COLLATE pg_catalog."default",
    is_admin boolean NOT NULL DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_user_name_key UNIQUE (user_name)
);

DROP TABLE IF EXISTS public.words;

CREATE TABLE IF NOT EXISTS public.words
(
    word_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    word character varying COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default" NOT NULL,
    difficulty integer NOT NULL DEFAULT 100,
    CONSTRAINT words_pkey PRIMARY KEY (word_id),
    CONSTRAINT words_word_key UNIQUE (word)
);

ALTER TABLE IF EXISTS public.game_rounds
    ADD CONSTRAINT game_rounds_game_id_fkey FOREIGN KEY (game_id)
    REFERENCES public.games (game_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.game_rounds
    ADD CONSTRAINT game_rounds_round_id_fkey FOREIGN KEY (round_id)
    REFERENCES public.rounds (round_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.games
    ADD CONSTRAINT games_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.games
    ADD CONSTRAINT games_word_id_fkey FOREIGN KEY (word_id)
    REFERENCES public.words (word_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.prises
    ADD CONSTRAINT prises_categorie_id_fkey FOREIGN KEY (categorie_id)
    REFERENCES public.categorie (categorie_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rounds
    ADD CONSTRAINT rounds_prise_id_fkey FOREIGN KEY (prise_id)
    REFERENCES public.prises (prise_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


INSERT INTO words(word, description)
    values
	('сороконожка', 'насекомое, которое не любит обуваться'),
	('лейка', 'садовый инвентарь'),
	('джомолунгма', 'самая высокая гора'),
	('смехопанорама', 'веселая передача'),
	('пароход', 'Крузенштерн из простоквашино'),
	('слякоть', 'неприятная погода на дворе'),
	('Барселона', 'город, в котором находится известный долгострой'),
    ('СЕЛЬДЕРЕЙ','Однолетнее зеленое растение, трава, пряность. Используются листья, стебли и корни'),
    ('ГРАБЛИ','Садовый инструмент'),
    ('МОКРИЦА','Насекомое с большим количеством ног'),
    ('ДИКОБРАЗ','Ежик-переросток'),
    ('ПОВАРЕЖКА','Столовый прибор');


INSERT INTO scores(score)
	VALUES
    (10),
    (20),
    (30),
    (40),
    (50),
    (60),
    (70),
    (80),
    (90),
    (100);


INSERT INTO categories(categorie_name)
	VALUES
    ('Посуда'),
    ('Еда'),
    ('Инвентарь'),
    ('Бытовая химия'),
    ('Красота и здоровье'),
    ('Товары для животных');


INSERT INTO prises(prise_description, discount_value, price_in_scores, categorie_id)
	VALUES
    ('Сервиз какой-то матери, набор', 100, 0, 1),
    ('Ковер-самолет, шт', 100, 0, 3),
    ('Миксер, шт', 100, 0, 3),
    ('Крем "Молодильное яблоко", туба', 100, 0, 5),
    ('Колбаса рога-копытская, батон', 50, 45, 2),
    ('Заяц шоколадный, набор', 20, 70, 2),
    ('Супер лопата, шт', 15, 30, 3),
    ('Шлейка со стразамиб шт', 80, 100, 6),
    ('Гербалайф, бут', 45, 30, 5),
    ('Унивенрсальный пятновыводитель, бут', 90, 10, 4);


END;
"""