# Generated by Django 5.2 on 2025-05-10 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categorie_id', models.AutoField(primary_key=True, serialize=False)),
                ('categorie_name', models.CharField(verbose_name='Категория')),
                ('categorie_img', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['categorie_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('letters', models.CharField(max_length=33)),
            ],
            options={
                'db_table': 'games',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('round_id', models.AutoField(primary_key=True, serialize=False)),
                ('round_scores', models.IntegerField(blank=True, null=True)),
                ('is_word_guessed', models.BooleanField()),
            ],
            options={
                'db_table': 'rounds',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'scores',
                'ordering': ['score'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, null=True, unique=True)),
                ('password', models.CharField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('scores', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(unique=True)),
                ('description', models.CharField()),
                ('difficulty', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'words',
                'ordering': ['word'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prises',
            fields=[
                ('prise_id', models.AutoField(primary_key=True, serialize=False)),
                ('prise_description', models.CharField(verbose_name='Описание')),
                ('discount_value', models.IntegerField(verbose_name='Скидка, %')),
                ('price_in_scores', models.IntegerField(verbose_name='Стоимость, очки')),
                ('to_show', models.BooleanField(blank=True, verbose_name='Видимость')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.categories', verbose_name='Категория')),
            ],
            options={
                'db_table': 'prises',
                'ordering': ['categorie_id', 'prise_description'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GameRounds',
            fields=[
                ('gr_id', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.games')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.rounds')),
            ],
            options={
                'db_table': 'game_rounds',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='games',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.users'),
        ),
        migrations.CreateModel(
            name='UsersPrises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.prises')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.users')),
            ],
            options={
                'db_table': 'users_prises',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='games',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.words'),
        ),
    ]
