# Generated by Django 5.2 on 2025-05-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prises',
            name='to_show',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
