# Generated by Django 5.2 on 2025-05-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': False, 'ordering': ['categorie_id']},
        ),
        migrations.AlterModelOptions(
            name='prises',
            options={'managed': False, 'ordering': ['categorie_id', 'prise_description']},
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={'managed': False, 'ordering': ['score']},
        ),
        migrations.AlterModelOptions(
            name='words',
            options={'managed': False, 'ordering': ['word']},
        ),
    ]
