# Generated by Django 5.2 on 2025-05-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_alter_categories_options_alter_prises_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': True, 'ordering': ['categorie_id']},
        ),
        migrations.AlterModelOptions(
            name='gamerounds',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='prises',
            options={'managed': True, 'ordering': ['categorie_id', 'prise_description']},
        ),
        migrations.AlterModelOptions(
            name='rounds',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={'managed': True, 'ordering': ['score']},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usersprises',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='words',
            options={'managed': True, 'ordering': ['word']},
        ),
    ]
