# Generated by Django 5.2 on 2025-05-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_alter_prises_to_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categorie_img',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
