# Generated by Django 5.2 on 2025-05-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_alter_categories_categorie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categorie_img',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
