# Generated by Django 5.2 on 2025-05-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0006_alter_games_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='letters',
            field=models.CharField(blank=True, default='', max_length=33, null=True),
        ),
    ]
