# Generated by Django 5.2 on 2025-04-30 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('prise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.prises')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.users')),
            ],
        ),
    ]
