-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.cities DROP CONSTRAINT IF EXISTS cities_zip_id_fkey;

ALTER TABLE IF EXISTS public.countries DROP CONSTRAINT IF EXISTS countries_zip_id_fkey;

ALTER TABLE IF EXISTS public.facebooks DROP CONSTRAINT IF EXISTS facebooks_market_id_fkey;

ALTER TABLE IF EXISTS public.market_location DROP CONSTRAINT IF EXISTS market_location_location_id_fkey;

ALTER TABLE IF EXISTS public.market_location DROP CONSTRAINT IF EXISTS market_location_market_id_fkey;

ALTER TABLE IF EXISTS public.market_merch DROP CONSTRAINT IF EXISTS market_merch_market_id_fkey;

ALTER TABLE IF EXISTS public.market_merch DROP CONSTRAINT IF EXISTS market_merch_merch_id_fkey;

ALTER TABLE IF EXISTS public.market_payment DROP CONSTRAINT IF EXISTS market_payment_market_id_fkey;

ALTER TABLE IF EXISTS public.market_payment DROP CONSTRAINT IF EXISTS market_payment_payment_id_fkey;

ALTER TABLE IF EXISTS public.market_season DROP CONSTRAINT IF EXISTS market_season_market_id_fkey;

ALTER TABLE IF EXISTS public.market_season DROP CONSTRAINT IF EXISTS market_season_season_id_fkey;

ALTER TABLE IF EXISTS public.market_upd DROP CONSTRAINT IF EXISTS market_upd_market_id_fkey;

ALTER TABLE IF EXISTS public.market_upd DROP CONSTRAINT IF EXISTS market_upd_upd_id_fkey;

ALTER TABLE IF EXISTS public.markets DROP CONSTRAINT IF EXISTS markets_coordinates_id_fkey;

ALTER TABLE IF EXISTS public.markets DROP CONSTRAINT IF EXISTS markets_street_id_fkey;

ALTER TABLE IF EXISTS public.markets DROP CONSTRAINT IF EXISTS markets_zip_id_fkey;

ALTER TABLE IF EXISTS public.othermedias DROP CONSTRAINT IF EXISTS othermedias_market_id_fkey;

ALTER TABLE IF EXISTS public.states DROP CONSTRAINT IF EXISTS states_zip_id_fkey;

ALTER TABLE IF EXISTS public.tweetters DROP CONSTRAINT IF EXISTS tweetters_market_id_fkey;

ALTER TABLE IF EXISTS public.websites DROP CONSTRAINT IF EXISTS websites_market_id_fkey;

ALTER TABLE IF EXISTS public.youtubes DROP CONSTRAINT IF EXISTS youtubes_market_id_fkey;



DROP TABLE IF EXISTS public.cities;

CREATE TABLE IF NOT EXISTS public.cities
(
    city_id integer NOT NULL,
    zip_id integer,
    city_name character(100) COLLATE pg_catalog."default",
    CONSTRAINT cities_pkey PRIMARY KEY (city_id)
);

DROP TABLE IF EXISTS public.coordinates;

CREATE TABLE IF NOT EXISTS public.coordinates
(
    coordinates_id integer NOT NULL,
    x_coord real,
    y_coord real,
    CONSTRAINT coordinates_pkey PRIMARY KEY (coordinates_id)
);

DROP TABLE IF EXISTS public.countries;

CREATE TABLE IF NOT EXISTS public.countries
(
    country_id integer NOT NULL,
    country_name character(100) COLLATE pg_catalog."default",
    zip_id integer,
    CONSTRAINT countries_pkey PRIMARY KEY (country_id)
);

DROP TABLE IF EXISTS public.facebooks;

CREATE TABLE IF NOT EXISTS public.facebooks
(
    fb_address text COLLATE pg_catalog."default",
    market_id integer
);

DROP TABLE IF EXISTS public.locations;

CREATE TABLE IF NOT EXISTS public.locations
(
    location_id integer NOT NULL,
    location_name character(50) COLLATE pg_catalog."default",
    CONSTRAINT locations_pkey PRIMARY KEY (location_id)
);

DROP TABLE IF EXISTS public.market_location;

CREATE TABLE IF NOT EXISTS public.market_location
(
    market_id integer,
    location_id integer
);

DROP TABLE IF EXISTS public.market_merch;

CREATE TABLE IF NOT EXISTS public.market_merch
(
    market_id integer,
    merch_id integer
);

DROP TABLE IF EXISTS public.market_payment;

CREATE TABLE IF NOT EXISTS public.market_payment
(
    market_id integer,
    payment_id integer
);

DROP TABLE IF EXISTS public.market_season;

CREATE TABLE IF NOT EXISTS public.market_season
(
    market_id integer,
    season_id integer
);

DROP TABLE IF EXISTS public.market_upd;

CREATE TABLE IF NOT EXISTS public.market_upd
(
    market_id integer,
    upd_id integer
);

DROP TABLE IF EXISTS public.markets;

CREATE TABLE IF NOT EXISTS public.markets
(
    market_id integer NOT NULL,
    market_name character(250) COLLATE pg_catalog."default",
    street_id integer,
    zip_id integer,
    coordinates_id integer,
    CONSTRAINT markets_pkey PRIMARY KEY (market_id)
);

DROP TABLE IF EXISTS public.merchandise;

CREATE TABLE IF NOT EXISTS public.merchandise
(
    merchandise_id integer NOT NULL,
    merchandise_name character(50) COLLATE pg_catalog."default",
    CONSTRAINT merchandise_pkey PRIMARY KEY (merchandise_id)
);

DROP TABLE IF EXISTS public.othermedias;

CREATE TABLE IF NOT EXISTS public.othermedias
(
    media_link text COLLATE pg_catalog."default",
    market_id integer
);

DROP TABLE IF EXISTS public.payments;

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id integer NOT NULL,
    payment_method character(10) COLLATE pg_catalog."default",
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

DROP TABLE IF EXISTS public.seasons;

CREATE TABLE IF NOT EXISTS public.seasons
(
    season_id integer NOT NULL,
    date_start date,
    date_end date,
    day_of_week character(5) COLLATE pg_catalog."default",
    time_start time without time zone,
    time_end time without time zone,
    CONSTRAINT seasons_pkey PRIMARY KEY (season_id)
);

DROP TABLE IF EXISTS public.states;

CREATE TABLE IF NOT EXISTS public.states
(
    state_id integer NOT NULL,
    state_name character(100) COLLATE pg_catalog."default",
    zip_id integer,
    CONSTRAINT states_pkey PRIMARY KEY (state_id)
);

DROP TABLE IF EXISTS public.streets;

CREATE TABLE IF NOT EXISTS public.streets
(
    street_id integer NOT NULL,
    street_name character(250) COLLATE pg_catalog."default",
    CONSTRAINT streets_pkey PRIMARY KEY (street_id)
);

DROP TABLE IF EXISTS public.tweetters;

CREATE TABLE IF NOT EXISTS public.tweetters
(
    tweetter text COLLATE pg_catalog."default",
    market_id integer
);

DROP TABLE IF EXISTS public.update_date;

CREATE TABLE IF NOT EXISTS public.update_date
(
    date_id integer NOT NULL,
    upd_time timestamp without time zone,
    CONSTRAINT update_date_pkey PRIMARY KEY (date_id)
);

DROP TABLE IF EXISTS public.websites;

CREATE TABLE IF NOT EXISTS public.websites
(
    web_link text COLLATE pg_catalog."default",
    market_id integer
);

DROP TABLE IF EXISTS public.youtubes;

CREATE TABLE IF NOT EXISTS public.youtubes
(
    youtube_link text COLLATE pg_catalog."default",
    market_id integer
);

DROP TABLE IF EXISTS public.zips;

CREATE TABLE IF NOT EXISTS public.zips
(
    zip_id integer NOT NULL,
    zip_code text COLLATE pg_catalog."default",
    CONSTRAINT zips_pkey PRIMARY KEY (zip_id)
);

COMMENT ON TABLE public.zips
    IS 'zip codes';

ALTER TABLE IF EXISTS public.cities
    ADD CONSTRAINT cities_zip_id_fkey FOREIGN KEY (zip_id)
    REFERENCES public.zips (zip_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.countries
    ADD CONSTRAINT countries_zip_id_fkey FOREIGN KEY (zip_id)
    REFERENCES public.zips (zip_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.facebooks
    ADD CONSTRAINT facebooks_market_id_fkey FOREIGN KEY (market_id)
    REFERENCES public.markets (market_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.market_location
    ADD CONSTRAINT market_location_location_id_fkey FOREIGN KEY (location_id)
    REFERENCES public.locations (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.market_location
    ADD CONSTRAINT market_location_market_id_fkey FOREIGN KEY (market_id)
    REFERENCES public.markets (market_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.market_merch
    ADD CONSTRAINT market_merch_market_id_fkey FOREIGN KEY (market_id)
    REFERENCES public.markets (market_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.market_merch
    ADD CONSTRAINT market_merch_merch_id_fkey FOREIGN KEY (merch_id)
    REFERENCES public.merchandise (merchandise_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.market_payment
    ADD CONSTRAINT market_payment_market_id_fkey FOREIGN KEY (market_id)
    REFERENCES public.markets (market_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.market_payment
    ADD CONSTRAINT market_payment_payment_id_fkey FOREIGN KEY (payment_id)
    REFERENCES public.payments (payment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.market_season
    ADD CONSTRAINT market_season_market_id_fkey FOREIGN KEY (market_id)
    REFERENCES public.markets (market_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.market_season
    ADD CONSTRAINT market_season_season_id_fkey FOREIGN KEY (season_id)
    REFERENCES public.seasons (season_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.market_upd
    ADD CONSTRAINT market_upd_market_id_fkey FOREIGN KEY (market_id)
    REFERENCES public.markets (market_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.market_upd
    ADD CONSTRAINT market_upd_upd_id_fkey FOREIGN KEY (upd_id)
    REFERENCES public.update_date (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.markets
    ADD CONSTRAINT markets_coordinates_id_fkey FOREIGN KEY (coordinates_id)
    REFERENCES public.coordinates (coordinates_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.markets
    ADD CONSTRAINT markets_street_id_fkey FOREIGN KEY (street_id)
    REFERENCES public.streets (street_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.markets
    ADD CONSTRAINT markets_zip_id_fkey FOREIGN KEY (zip_id)
    REFERENCES public.zips (zip_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.othermedias
    ADD CONSTRAINT othermedias_market_id_fkey FOREIGN KEY (market_id)
    REFERENCES public.markets (market_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.states
    ADD CONSTRAINT states_zip_id_fkey FOREIGN KEY (zip_id)
    REFERENCES public.zips (zip_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tweetters
    ADD CONSTRAINT tweetters_market_id_fkey FOREIGN KEY (market_id)
    REFERENCES public.markets (market_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.websites
    ADD CONSTRAINT websites_market_id_fkey FOREIGN KEY (market_id)
    REFERENCES public.markets (market_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.youtubes
    ADD CONSTRAINT youtubes_market_id_fkey FOREIGN KEY (market_id)
    REFERENCES public.markets (market_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;